/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddParticipantModal: typeof import('./src/components/Registration/AddParticipantModal.vue')['default']
    BottomSheet: typeof import('./src/components/Common/BottomSheet.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StepConfirmation: typeof import('./src/components/Registration/StepConfirmation.vue')['default']
    StepInfo: typeof import('./src/components/Registration/StepInfo.vue')['default']
    StepParticipants: typeof import('./src/components/Registration/StepParticipants.vue')['default']
    StepSchedule: typeof import('./src/components/Registration/StepSchedule.vue')['default']
    StepUser: typeof import('./src/components/Registration/StepUser.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
